#pragma config(Sensor, S1,     cam,            sensorNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mindsensors-nxtcam.h"

//// short xscale(short x) - Scales x values from camera coordinates to screen coordinates.
//long xscale(long x) {
//  return ((x - 12) * 177) / 175;
//}

//// short yscale(short y) - Scales y values from camera coordinates to screen coordinates.
//long yscale(long y) {
//  return ((143 - y) * 127) / 143;
//}

task main() {
	blob_array blobs;
  // combine all colliding blobs into one
  bool _condensed = true;

  //blob_array _blobs;
	short nblobs;
	short couleur, max_size;

	displayBigTextLine(1, "CAM");
	NXTCAMinit(cam);


  while (true) {
  	nblobs = NXTCAMgetBlobs(cam, blobs, _condensed);
  	couleur = -1;
  	max_size = 0;
    for (short i = 0; i < nblobs; i++) {
    	if (blobs[i].size > 400 && blobs[i].size > max_size) {
      	couleur = blobs[i].colour;
      	max_size = blobs[i].size;
   		}
		}
		if (couleur==0) {
			displayBigTextLine(3, "BLEU ");
		}
		else if (couleur==1) {
			displayBigTextLine(3, "ROUGE");
		}
		else {
			displayBigTextLine(3, "RIEN "); //%d %d %d", couleur,max_size,nblobs);
		}
		wait10Msec(10);
	}
}
